name: Main CI Pipeline
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - run: zip -r QuakeDev.zip .
    - name: Add to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: QuakeDev.zip
        asset_name: QuakeDev
        tag: ${{ github.ref }}
        overwrite: true
        body: "Michael's Super Cool Release"