name: Main CI Pipeline
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Archive data
      uses: actions/upload-artifact@v3
      with:
        name: QuakeDev
        path: ./
